# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: master_worker.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'master_worker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13master_worker.proto\x12\rmaster_worker\"`\n\x10HeartbeatRequest\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12\x16\n\x0eworker_address\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x12\x0e\n\x06status\x18\x04 \x01(\t\"O\n\x11HeartbeatResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x18\n\x10master_timestamp\x18\x03 \x01(\x03\"^\n\x0fRegisterRequest\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12\x16\n\x0eworker_address\x18\x02 \x01(\t\x12\x10\n\x08\x63pu_core\x18\x03 \x01(\x05\x12\x0e\n\x06memory\x18\x04 \x01(\x03\"L\n\x10RegisterResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x16\n\x0emaster_address\x18\x03 \x01(\t2\xb0\x01\n\rMasterService\x12K\n\x08Register\x12\x1e.master_worker.RegisterRequest\x1a\x1f.master_worker.RegisterResponse\x12R\n\rSendHeartbeat\x12\x1f.master_worker.HeartbeatRequest\x1a .master_worker.HeartbeatResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'master_worker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEARTBEATREQUEST']._serialized_start=38
  _globals['_HEARTBEATREQUEST']._serialized_end=134
  _globals['_HEARTBEATRESPONSE']._serialized_start=136
  _globals['_HEARTBEATRESPONSE']._serialized_end=215
  _globals['_REGISTERREQUEST']._serialized_start=217
  _globals['_REGISTERREQUEST']._serialized_end=311
  _globals['_REGISTERRESPONSE']._serialized_start=313
  _globals['_REGISTERRESPONSE']._serialized_end=389
  _globals['_MASTERSERVICE']._serialized_start=392
  _globals['_MASTERSERVICE']._serialized_end=568
# @@protoc_insertion_point(module_scope)
