# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: worker_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'worker_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14worker_service.proto\x12\x0eworker_service\"\xc0\x02\n\x08TaskData\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\x0e\n\x06method\x18\x03 \x01(\t\x12\x36\n\x07headers\x18\x04 \x03(\x0b\x32%.worker_service.TaskData.HeadersEntry\x12\x0c\n\x04\x62ody\x18\x05 \x01(\t\x12\x10\n\x08priority\x18\x06 \x01(\x05\x12\x13\n\x0bretry_count\x18\x07 \x01(\x05\x12\x38\n\x08metadata\x18\x08 \x03(\x0b\x32&.worker_service.TaskData.MetadataEntry\x1a.\n\x0cHeadersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"e\n\x15\x44istributeTaskRequest\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12&\n\x04task\x18\x02 \x01(\x0b\x32\x18.worker_service.TaskData\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\"e\n\x16\x44istributeTaskResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07task_id\x18\x03 \x01(\t\x12\x18\n\x10worker_timestamp\x18\x04 \x01(\x03\"j\n\x11TaskStatusRequest\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12\x0f\n\x07task_id\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\x05\x12\x0e\n\x06result\x18\x04 \x01(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\x03\"P\n\x12TaskStatusResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x18\n\x10master_timestamp\x18\x03 \x01(\x03\x32\xcb\x01\n\rWorkerService\x12_\n\x0e\x44istributeTask\x12%.worker_service.DistributeTaskRequest\x1a&.worker_service.DistributeTaskResponse\x12Y\n\x10UpdateTaskStatus\x12!.worker_service.TaskStatusRequest\x1a\".worker_service.TaskStatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'worker_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TASKDATA_HEADERSENTRY']._loaded_options = None
  _globals['_TASKDATA_HEADERSENTRY']._serialized_options = b'8\001'
  _globals['_TASKDATA_METADATAENTRY']._loaded_options = None
  _globals['_TASKDATA_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_TASKDATA']._serialized_start=41
  _globals['_TASKDATA']._serialized_end=361
  _globals['_TASKDATA_HEADERSENTRY']._serialized_start=266
  _globals['_TASKDATA_HEADERSENTRY']._serialized_end=312
  _globals['_TASKDATA_METADATAENTRY']._serialized_start=314
  _globals['_TASKDATA_METADATAENTRY']._serialized_end=361
  _globals['_DISTRIBUTETASKREQUEST']._serialized_start=363
  _globals['_DISTRIBUTETASKREQUEST']._serialized_end=464
  _globals['_DISTRIBUTETASKRESPONSE']._serialized_start=466
  _globals['_DISTRIBUTETASKRESPONSE']._serialized_end=567
  _globals['_TASKSTATUSREQUEST']._serialized_start=569
  _globals['_TASKSTATUSREQUEST']._serialized_end=675
  _globals['_TASKSTATUSRESPONSE']._serialized_start=677
  _globals['_TASKSTATUSRESPONSE']._serialized_end=757
  _globals['_WORKERSERVICE']._serialized_start=760
  _globals['_WORKERSERVICE']._serialized_end=963
# @@protoc_insertion_point(module_scope)
