# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import dspider.worker.rpc.worker_service_pb2 as worker__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in worker_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorkerServiceStub(object):
    """定义主节点服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DistributeTask = channel.unary_unary(
                '/worker_service.WorkerService/DistributeTask',
                request_serializer=worker__service__pb2.DistributeTaskRequest.SerializeToString,
                response_deserializer=worker__service__pb2.DistributeTaskResponse.FromString,
                _registered_method=True)
        self.UpdateTaskStatus = channel.unary_unary(
                '/worker_service.WorkerService/UpdateTaskStatus',
                request_serializer=worker__service__pb2.TaskStatusRequest.SerializeToString,
                response_deserializer=worker__service__pb2.TaskStatusResponse.FromString,
                _registered_method=True)


class WorkerServiceServicer(object):
    """定义主节点服务
    """

    def DistributeTask(self, request, context):
        """任务分发接口
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTaskStatus(self, request, context):
        """任务状态更新接口
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DistributeTask': grpc.unary_unary_rpc_method_handler(
                    servicer.DistributeTask,
                    request_deserializer=worker__service__pb2.DistributeTaskRequest.FromString,
                    response_serializer=worker__service__pb2.DistributeTaskResponse.SerializeToString,
            ),
            'UpdateTaskStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTaskStatus,
                    request_deserializer=worker__service__pb2.TaskStatusRequest.FromString,
                    response_serializer=worker__service__pb2.TaskStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'worker_service.WorkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('worker_service.WorkerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkerService(object):
    """定义主节点服务
    """

    @staticmethod
    def DistributeTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/worker_service.WorkerService/DistributeTask',
            worker__service__pb2.DistributeTaskRequest.SerializeToString,
            worker__service__pb2.DistributeTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateTaskStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/worker_service.WorkerService/UpdateTaskStatus',
            worker__service__pb2.TaskStatusRequest.SerializeToString,
            worker__service__pb2.TaskStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
